# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Pacman Theme"
license = "MIT"
licenselink = "https://github.com/jacpy/hugo-pacman-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://blog.jacpy.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "jacpy"
  homepage = "http://blog.jacpy.com"

# If porting an existing theme
[original]
  name = "pacman"
  homepage = "https://github.com/A-limon/pacman"
  repo = "https://github.com/A-limon/pacman"
